### ISSUE TITLE
Gap between stacked polygons

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol3#5303]
I am rendering a series of stacked polygons. However, and even though vertex coordinates use the same numbers, the rendering leaves intermittent gaps between them. This happens in both Firefox and Chrome.

![screenshot from 2016-05-02 17-40-06](https://cloud.githubusercontent.com/assets/3722516/14960996/64352e1a-108f-11e6-9cca-1103f551084f.png)

Source: https://jsfiddle.net/adlerhn/v5L3poqz/1/

**Comment by ahocevar** [comment]
I don't know why this happens. Probably has to do with how the browser implements polygon fills in the Canvas 2D API. A workaround is to add a 1 pixel stroke: http://jsfiddle.net/v5L3poqz/3/

**Comment by jmgomezpoveda** [comment]
That workaround works fine if the polygons are opaque. But for semi-transparent polygons, that actually makes the problem worse: http://jsfiddle.net/v5L3poqz/4/

**Comment by ahocevar** [comment]
See http://stackoverflow.com/questions/29355920/canvas-polygons-not-touching-properly#29357697. As I suspsected, this is a problem with browser implementations of the Canvas 2D API, which automatically apply anti-aliasing.

http://jsfiddle.net/v5L3poqz/5/ gives a better (but not perfect) visual result - by adding a 1/8 px wide stroke, with 1/4 of the opacity of the fill.

**Comment by jmgomezpoveda** [comment]
The issue does not happen when stacking polygons using the Google Maps API, which also renders them into canvases. Maybe they use their own rendering library?

**Comment by jmgomezpoveda** [comment]
Thanks for the research and the effort with the workarounds, though I don't think they improves much (but that's just my perception).

Also, adding these 1/8 borders to the polygons makes lines appear when switching to the 3D view (using ol3-cesium), which works perfectly by default.

**Comment by ahocevar** [comment]
One interesting observation is that this does not seem to happen with vector tiles. Here are two screenshots. The first shows polygon boundaries (across vector tiles) with a stroke applied (so they are visible), the second shows these polygons touching properly without gaps:

<img width="1117" alt="stroke" src="https://cloud.githubusercontent.com/assets/211514/15232012/b159eeee-189e-11e6-98cc-1f6ae14931f0.png">

<img width="1117" alt="no-stroke" src="https://cloud.githubusercontent.com/assets/211514/15232016/b7981ede-189e-11e6-8dba-b88dd153fac8.png">

**Comment by jmgomezpoveda** [comment]
As a reference, a fiddle using the Google Maps API: https://jsfiddle.net/adlerhn/d3x07j4o/

**Comment by fredj** [comment]
Updated jsfiddle: http://jsfiddle.net/fredj/ff1L089u/

**Comment by ahocevar** [comment]
And finally, issue fixed with #5196. By applying the new `overlaps: false` option to the layer source, you get the desired behaviour: http://jsfiddle.net/ff1L089u/1/.

**Comment by jmgomezpoveda** [comment]
Great! I will implement it in my site today or tomorrow.

**Comment by jmgomezpoveda** [comment]
I just tested it, and only solves the issue for one particular use case: batches of polygons sent in one go.

If polygons are added separately (because they are to have a different colour), the lines still appear: http://jsfiddle.net/m2ayx4sy/1/

**Comment by jmgomezpoveda** [comment]
Actually, this is a better Fiddle, with all features in one vector layer: http://jsfiddle.net/m2ayx4sy/2/

**Comment by ahocevar** [comment]
I'd be interested to hear what your use case is @jmgomezpoveda. To me your last two fiddles look like an absolute rare corner case.

**Comment by jmgomezpoveda** [comment]
I have a matrix that cover the whole world, with a different intensity per coordinate. So, I want to overlay these intensities on the world map, using a vector layer.

I am dividing he world coordinates by the resolution of this matrix, and creating polygons with a colour that depends on the value of this location in the matrix of intensities. So I end up with a few thousand polygons of different colours next to each other.

Actually, to decrease the number of polygons, I create only one polygon for every span of consecutive coordinates that share the same value.

I originally implemented this in Google Maps, but when migrating it to OpenLayers I have observed these gaps:

![matrix](https://cloud.githubusercontent.com/assets/3722516/18218770/f7aaf6ce-715c-11e6-9b8a-123659fddf46.png)

I could see this as a very generic use case (overlay a matrix of values on top of the world map).

**Comment by ahocevar** [comment]
This is a perfect use case for an ol.source.Raster with a source image that matches your grid. Much nicer than simulating raster cells with vector features.

**Comment by ischas** [comment]
What about a classified world map where each country has it's own color?

**Comment by jmgomezpoveda** [comment]
Thanks for the suggestion. I have looked into ol.source.Raster and I am not clear on how could I make use of it, so I have created a question on StackExchange: http://gis.stackexchange.com/questions/209462/overlaying-a-matrix-of-intensities-over-the-world-map
