### ISSUE TITLE
requestAnimationFrame ie9

### ISSUE THREAD

**Issue by phendji** [openlayers/ol3#5337]
openlayers  Version: v3.14.2 doesn't support requestAnimationFrame on ie9. But when i use openlayers  Version: v3.0.0 I do not have any error.
Maybe  a regression ?????

**Comment by tsauerwein** [comment]
See https://github.com/openlayers/ol3/blob/master/changelog/upgrade-notes.md#v3140

**Comment by cs09g** [comment]
with IE development tool's version setting from Edge to 9, it doesn't work for me. =(
should be working?

**Comment by ahocevar** [comment]
Maybe the version setting confuses the polyfill.io loader. But in a real IE9, it should be working.

**Comment by cs09g** [comment]
@ahocevar Thank you!

**Comment by ischas** [comment]
Maybe you have missed to change the user agent in the IE Dev Tools?

**Comment by cs09g** [comment]
@ischas I tried changing both but still shows the same error. I need to check their issue list.

**Comment by phendji** [comment]
@cs09g can you show us your error ??

**Comment by ischas** [comment]
If you want to debug old versions of IE you should have a look at this site: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by cs09g** [comment]
@phendji that is "SCRIPT438: Object doesn't support this property or method" error. 
@ischas Thank you. It's good one.

**Comment by phendji** [comment]
@cs09g look at here and say me: https://github.com/jdorn/json-editor/issues/78

**Comment by cs09g** [comment]
@phendji about to add 
```window.requestAnimationFrame = window.requestAnimationFrame || function(callback) { window.setTimeout(callback,16) };```

it causes another one. SCRIPT5007 error. 16 ms to 1600 ms causes the same.

**Comment by phendji** [comment]
@cs09g I don't have another solution. Change version openlayers

**Comment by ahocevar** [comment]
Please, stop this discussion and follow the recommendation given [above](https://github.com/openlayers/ol3/issues/5337#issuecomment-234487953)
